[package]
authors = ["Tyler Holmes <tylerdanielholmes@gmail.com>"]
edition = "2018"
name = "oven-temp-rs"
version = "0.1.0"

[dependencies]
embedded-hal = "0.2"
feather_m0 = {features = ["unproven","usb"], git = "https://github.com/atsamd-rs/atsamd"}
# feather_m0 = {path = "/Users/tholmes/projects/rust/atsamd/boards/feather_m0", features = ["unproven"]}
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
panic-halt = {version = "0.2.0"}
panic-semihosting = {version = "0.5"}
cortex-m-semihosting = "0.3"
usb-device = "~0.2"
usbd-serial = "~0.1"

[features]
# no features by default
default = []
# usbserial feature doesn't depend on any others
usbserial = []

# this lets you use `cargo fix`!
[[bin]]
name = "oven-temp-rs"
test = false
bench = false

[profile.release]
codegen-units = 1   # better optimizations
debug = true        # symbols are nice and they don't increase the size on Flash
lto = true          # better optimizations
opt-level = "s"

[profile.dev]  # Doesn't fit on chip otherwise
codegen-units = 1   # better optimizations
debug = true        # symbols are nice and they don't increase the size on Flash
opt-level = 1
