name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      run: cargo build --verbose
    - name: Build w USB feature
      run: cargo build --verbose --features usbserial
    - name: Run tests
      run: cargo test --verbose
