name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup target add thumbv6m-none-eabi && rustup component add clippy
    - name: Build (default features)
      run: cargo build --verbose
    - name: Build (USB feature)
      run: cargo build --verbose --features usbserial
    - name: Build (no features)
      run: cargo build --verbose --no-default-features
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
